variables:
  configuration: release

pool:
  vmImage: 'windows-2019'

trigger:
  batch: false
  branches:
    include:
      - master
    paths:
      include:
      - '/'
      exclude:
      - 'readme.md'
      - 'docs/'

steps:
- checkout: self
  submodules: true
  
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: 'custom'
    custom: pack
    arguments: './src/neo-express/neo-express.csproj --version-suffix preview-$(Build.BuildNumber) -c $(configuration) -o $(Build.ArtifactStagingDirectory) --include-symbols'

- publish: '$(Build.ArtifactStagingDirectory)'
  displayName: 'publish build artifact'
  name: nugetPackage

- task: NuGetCommand@2
  displayName: 'NuGet push to private feed'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'e4a31b7b-a6f8-4d1e-92d1-92d68bffefe3'