variables:
  configuration: release

pool:
  vmImage: 'windows-2019'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: 'custom'
    custom: pack
    arguments: '--version-suffix ngdsea-ci -c $(configuration) -o $(Build.ArtifactStagingDirectory) --include-symbols'

- task: PublishBuildArtifacts@1
  displayName: 'publish build artifacts'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'nuget package'

- task: NuGetCommand@2
  displayName: 'nuget push'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'd535200a-32cd-47f9-a782-a2f0a59e6c6a'
