variables:
  configuration: Release

pool:
  vmImage: 'windows-2019'

trigger:
  batch: false
  branches:
    include:
      - master
      - development
  paths:
    include:
    - '*'
    exclude:
    - 'readme.md'
    - 'docs/*'

name: $(Year:yy)$(DayOfYear)$(Rev:.r)

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $suffix = if ([string]::Equals($env:BUILD_SOURCEBRANCHNAME, "master", [System.StringComparison]::OrdinalIgnoreCase)) {
        "preview"
      } else {
        $env:BUILD_SOURCEBRANCHNAME.ToLower()
      }
      Write-Host "##vso[task.setvariable variable=versionSuffix;]$suffix"
    pwsh: true

- template: steps-build.yml
  parameters:
    versionSuffix: $(versionSuffix)
    configuration: $(configuration) 

- task: NuGetCommand@2
  displayName: 'NuGet push to private feed'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'e4a31b7b-a6f8-4d1e-92d1-92d68bffefe3'